id: I56194B9D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:00:00+00:00'
last_modified: '2022-06-08T09:30:02.758883+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14673
  title: ཙཱ་རིའི་གནས་ཡིག་འབར་བ་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    3C1C:
      image_group_id: I1KG15756
      title: ''
      total_pages: 152
      order: 1
      base_file: 3C1C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
