id: P009224
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:28:49.738678
source_metadata:
  id: bdr:W1KG14673
  title: ཙཱ་རིའི་གནས་ཡིག་འབར་བ་རྒྱལ་མཚན།
  author: ''
  volumes:
    6de3a3d6ccd54e94b1ca6ae5619dc0e2:
      image_group_id: I1KG15756
      title: ''
      volume_number: 1
      total_pages: 152
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
